SET GLOBAL time_zone = '+8:00';
DROP DATABASE IF EXISTS CL2_MAMANI_USCAMAYTA;
CREATE DATABASE CL2_MAMANI_USCAMAYTA;
USE CL2_MAMANI_USCAMAYTA;

CREATE TABLE AREA(
CODIGO_AREA INT NOT NULL auto_increment PRIMARY KEY,
AREA_NOMBRE VARCHAR(25),
AREA_JEFE VARCHAR (50)
);
CREATE TABLE PERSONAL(
	PERSONAL_ID INT PRIMARY KEY,
    PERSONAL_NOMBRE VARCHAR(255) NOT NULL,
    PERSONAL_CODIGO VARCHAR(255) NOT NULL,
    PERSONAL_SUELDO DOUBLE NOT NULL,
	CODIGO_AREA INT NOT NULL,
FOREIGN KEY (CODIGO_AREA) REFERENCES AREA(CODIGO_AREA)	
);

INSERT INTO AREA (CODIGO_AREA, AREA_NOMBRE, AREA_JEFE) VALUES
(1, 'Área 1', 'Jefe 1'),
(2, 'Área 2', 'Jefe 2'),
(3, 'Área 3', 'Jefe 3');

-- Insertar personal
INSERT INTO PERSONAL (PERSONAL_ID, PERSONAL_NOMBRE, PERSONAL_CODIGO, PERSONAL_SUELDO, CODIGO_AREA) VALUES
(1, 'Personal 1', 'COD1', 1000.00, 1),
(2, 'Personal 2', 'COD2', 2000.00, 1),
(3, 'Personal 3', 'COD3', 1500.00, 2),
(4, 'Personal 4', 'COD4', 1800.00, 2),
(5, 'Personal 5', 'COD5', 1200.00, 2),
(6, 'Personal 6', 'COD6', 2500.00, 3),
(7, 'Personal 7', 'COD7', 1700.00, 3),
(8, 'Personal 8', 'COD8', 1900.00, 3);

SELECT p.*, a.AREA_JEFE
FROM Personal p
INNER JOIN Area a ON p.codigo_area = a.codigo_area;